\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		f1 c1 bes1 c1

		% santo, santo, santo...
		f1 c1 bes1 c1
		f1 c1 bes1 c1

		% dioos del univeeersoo...
		d1:m d1:m7+ d1:7m g1:6
		bes1 g1:m bes1 c1 c1

		% hosanna...
		f2 r2 d2:m r2 bes1 c1
		f1 d1:m bes1 c1

		% bendiiiito el que vieeenee...
		d1:m d1:m7+ d1:7m g1:6
		bes1 g1:m bes1 c1 c1

		% hosanna...
		f2 r2 d2:m r2 bes1 c1
		f1 d1:m bes1 bes1:m f1
	}
